### ISSUE TITLE
Getting bad requests 

### ISSUE THREAD

**Issue by O5ten** [enfuse/backstage-chatgpt-plugin#6]
Getting 400 bad request when making any request towards openai. Is this due to some openai changes of their api perhaps? 

```bash
[1] 2024-02-19T10:14:14.546Z backstage error Request failed with status code 400 type=errorHandler config=[object Object] request=[object Object] response=[object Object] isAxiosError=true toJSON=function toJSON() {
[1]     return {
[1]       // Standard
[1]       message: this.message,
[1]       name: this.name,
[1]       // Microsoft
[1]       description: this.description,
[1]       number: this.number,
[1]       // Mozilla
[1]       fileName: this.fileName,
[1]       lineNumber: this.lineNumber,
[1]       columnNumber: this.columnNumber,
[1]       stack: this.stack,
[1]       // Axios
[1]       config: this.config,
[1]       code: this.code,
[1]       status: this.response && this.response.status ? this.response.status : null
[1]     };
[1]   } stack=Error: Request failed with status code 400
[1]     at createError (/home/mikaelo/git/backstage/node_modules/openai/node_modules/axios/lib/core/createError.js:16:15)
[1]     at settle (/home/mikaelo/git/backstage/node_modules/openai/node_modules/axios/lib/core/settle.js:17:12)
[1]     at IncomingMessage.handleStreamEnd (/home/mikaelo/git/backstage/node_modules/openai/node_modules/axios/lib/adapters/http.js:322:11)
[1]     at IncomingMessage.emit (node:events:525:35)
[1]     at IncomingMessage.emit (node:domain:489:12)
[1]     at endReadableNT (node:internal/streams/readable:1359:12)
[1]     at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
```

**Comment by O5ten** [comment]
Still having this problem tbh.

**Comment by O5ten** [comment]
Still having the same problem..
